name = "DeferredAcceptanceUCLEconMSc"
uuid = "87092628-10c8-4d42-88d7-7f19440767df"
authors = ["Joao Granja"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
